### ISSUE TITLE
`createMintAndVault` not working

### ISSUE THREAD

**Issue by leonardgee** [saber-hq/saber-common#470]
```
TypeError: Blob.encode[amount] requires (length 8) Buffer as src
      at Blob.encode (node_modules/buffer-layout/lib/Layout.js:2321:13)
      at Structure.encode (node_modules/buffer-layout/lib/Layout.js:1263:26)
      at Function.createMintToInstruction (node_modules/@solana/spl-token/client/token.js:1745:16)
```

**Comment by leonardgee** [comment]
Fixed after changing to `u64`.
