### ISSUE TITLE
TypeError: fields must be array of Layout instances

### ISSUE THREAD

**Issue by drinksbydrew** [saber-hq/saber-common#486]
I'm getting an issue using the stableswap-sdk.

```
import { loadExchangeInfoFromSwapAccount, SWAP_PROGRAM_ID } from "@saberhq/stableswap-sdk";
```

Simply importing anything that imports `stableswap-sdk/src/instructions/layouts.ts` fails with this error:

```
/Users/andrew/w/x/node_modules/@solana/buffer-layout/lib/Layout.js:999
            throw new TypeError('fields must be array of Layout instances');
            ^

TypeError: fields must be array of Layout instances
    at new Structure (/Users/andrew/w/x/node_modules/@solana/buffer-layout/lib/Layout.js:999:19)
    at Object.exports.struct (/Users/andrew/w/x/node_modules/@solana/buffer-layout/lib/Layout.js:2373:57)
    at Object.<anonymous> (/Users/andrew/w/x/node_modules/@saberhq/stableswap-sdk/dist/cjs/state/layout.js:10:35)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/andrew/w/x/node_modules/@saberhq/stableswap-sdk/dist/cjs/instructions/layouts.js:7:18)
```

https://github.com/solana-labs/solana-program-library/issues/2683 suggests it's a package version issue.

I have

```
"@saberhq/stableswap-sdk": "^1.12.44",
"@solana/buffer-layout": "^4.0.0",
"@solana/spl-token": "^0.1.8",
"@solana/web3.js": "^1.34.0"
```

in my package.json.

Any idea what the issue is?

**Comment by adityabharadwaj198** [comment]
Hey, how did you fix this?

**Comment by adityabharadwaj198** [comment]
For anyone looking for a solve -> had to do 
`npm install @solana/spl-token
npm install @solana/buffer-layout`

`anchor test` worked fine after that

**Comment by AuroraLantean** [comment]
Also install `@solana/buffer-layout` v 4.0.1
